
-- the total revenue generated by male vs. female customers

select gender, SUM(purchase_amount) as revenue
from customer
group by gender
order by revenue desc

-- the customers who used a discount but still spent more than the average purchase amount

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and 
purchase_amount >= (select AVG(purchase_amount) from customer)

-- the top 5 products with the highest average review rating

select item_purchased as product,
	Round(avg(review_rating::numeric),2) as avg_rating  
from customer
group by item_purchased 
order by avg(review_rating) desc 
limit 5

-- Comparing the average Purchase Amounts between Standard and Express Shipping.

select	shipping_type,
		round(avg(purchase_amount),2) as average_amount
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type 

-- Comparing average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
       round(avg(purchase_amount),2) as avg_spend,
       sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

-- 5 products which have the highest percentage of purchases with discounts applied

select item_purchased, 
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer 
group by item_purchased 
order by discount_rate desc 
limit 5 ;

-- Segmenting customers into New, Returning, and Loyal based on their 
-- total number of previous purchases, and showing the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment
order by "Number of Customers" DESC ;


-- the top 3 most purchased products within each category
   

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- customers who are repeat buyers (more than 5 previous purchases) checking if they're likely to subscribe

select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status 

-- the revenue contribution of each age group

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;

-- customer level table 

SELECT 
    customer_id,
    COUNT(*) AS total_orders,
    SUM(purchase_amount) AS total_spent,
    AVG(purchase_amount) AS avg_order_value,
    MAX(previous_purchases) AS previous_purchases
FROM customer
GROUP BY customer_id
ORDER BY customer_id;

-- adding scoring based on purchases 

WITH customer_summary AS (
    SELECT 
        customer_id,
        COUNT(*) AS total_orders,
        SUM(purchase_amount) AS total_spent,
        AVG(purchase_amount) AS avg_order_value,
        MAX(previous_purchases) AS lifetime_purchases
    FROM customer
    GROUP BY customer_id
)

SELECT *,
       NTILE(5) OVER (ORDER BY lifetime_purchases DESC) AS f_score,
       NTILE(5) OVER (ORDER BY total_spent DESC) AS m_score
FROM customer_summary;

-- combining f and m scoring and creating a customer segment table 

WITH customer_summary AS (
    SELECT 
        customer_id,
        COUNT(*) AS total_orders,
        SUM(purchase_amount) AS total_spent,
        AVG(purchase_amount) AS avg_order_value,
        MAX(previous_purchases) AS lifetime_purchases
    FROM customer
    GROUP BY customer_id
),

scored AS (
    SELECT *,
           NTILE(5) OVER (ORDER BY lifetime_purchases DESC) AS f_score,
           NTILE(5) OVER (ORDER BY total_spent DESC) AS m_score
    FROM customer_summary
)

SELECT *,
       (f_score + m_score) AS fm_score,
       CASE 
           WHEN (f_score + m_score) >= 8 THEN 'Champions'
           WHEN (f_score + m_score) >= 6 THEN 'Loyal'
           WHEN (f_score + m_score) >= 4 THEN 'Potential'
           ELSE 'At Risk'
       END AS customer_segment
FROM scored;































